version: 2.1

setup: true

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  publish:
    machine:
      image: ubuntu-2204:2023.02.1
    resource_class: medium
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - setup
      - run: |
          gradle publish

commands:
  setup:
    steps:
      - checkout
      - run: gradle build --console=plain
      - store_artifacts:
          path: ~/project/build/libs

workflows:
  publish:
    jobs:
      - publish:
          context:
            - maven
          filters:
            tags:
              only:
                - /.*/
            branches:
              ignore:
                - /.*/
                
